name: iOS CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build App
        run: |
          xcodebuild \
            -project SwiftUICICDDemo.xcodeproj \
            -scheme SwiftUICICDDemo \
            -destination 'platform=iOS Simulator,name=iPhone 17' \
            clean build

      - name: Run Tests
        run: |
          xcodebuild \
            test \
            -enableCodeCoverage YES \
            -project SwiftUICICDDemo.xcodeproj \
            -scheme SwiftUICICDDemo \
            -destination 'platform=iOS Simulator,name=iPhone 17'

  deploy:
    needs: build-and-test
    runs-on: macos-15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy to TestFlight
        env:
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: fastlane beta