name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build App
        run: |
          xcodebuild \
          -project SwiftUICICDDemo.xcodeproj \
          -scheme SwiftUICICDDemo \
          -destination 'platform=iOS Simulator,name=iPhone 17' \
          clean build

      - name: Run Tests with Code Coverage
        run: |
          xcodebuild \
          test \
          -enableCodeCoverage YES \
          -project SwiftUICICDDemo.xcodeproj \
          -scheme SwiftUICICDDemo \
          -destination 'platform=iOS Simulator,name=iPhone 17'